using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace DataTool.Global
{
    public enum EExcelType { TABLE, TYPE, GROUP, LOCALIZATION, CONSTDATA, MAX };

    public enum ETargetType { NONE, CLIENT, SERVER, ALL, MAX };

    public enum EPath
    {
        ExcelData = 0,
        ExcelEnum,
        ExcelGroup,
        ExcelLocalization,        
        ExcelLocalizationSystem,
        ExcelLocalizationDuty,
        ProtoEnum,
        ConstData,        
        ServerData,
        ServerConstCode,
        ClientData,
        ClientCode,
        LocalizationData,
        SystemLocalizationData,
        DutyLocalizationData,
        VNRoot,
        ProtoClientDest,
        ProtoServerDest,        
        End
    }

    public enum ETargetClass
    {
        Cpp,
        Cs,        
        Csv
    }
    
    class GlobalVar
    {
        public const bool       HaveAuthority = false;
        public const string     APPVer = "v0.007";

        //DataFileClassManager
        

        // Key
        public const bool       USE_KEY = false;
        public const string     FILE_NAME_KEY = "Key.ini";
        public static string    EncKeyVer = string.Empty;
        public static string    EncKey = string.Empty;
        public const int        KeyVerSize = 16;
        public const int        KeySize = 32;
        
        public const string     DataExtension = ".bytes";
        public const string     CSVExtention = ".csv";

        public const string     EXPORT_CS_ENUM_NAME = "DataFileEnum.cs";
        public const string     EXPORT_CPP_ENUM_NAME = "DataTypeEnum.h";
        public const string     ENCRYPT_BATCH_NAME = "EncryptKeyToDB";

        public const string     FMT_INITIAL_FILE = "{0} 파일을 초기화 중입니다.";
        public const string     FMT_INITIAL_ERROR_NO_EXCEL = "{0}파일은 테이블 파일이 아닙니다.";
        public const string     FMT_PROCESS_FILE = "{0} 파일을 작업 중입니다.";
        public const string     FMT_LOADING_FILE = "{0} 파일을 불러오고 있습니다.";
        public const string     FMT_LOADEND_FILE = "{0} 파일을 불러왔습니다.";
        public const string     FMT_STOP_FILE = "{0} 파일 작업을 중지했습니다.";
        public const string     FMT_ERROR_FILE = "{0} 파일 파싱이 에러로 멈췄습니다.";
        public const string     FMT_FAIL_PROTO_ENUM_FILE = "Fail CreateProtoEnumFile.\n이유 : {0}";
        public const string     FMT_FAIL_UPLOAD_DB = "Upload DB Fail.\n이유 : {0}";
        public const string     FMT_LOG = "[{0} Log]\n\n[Output]\n{1}\n[Error]\n{2}";
        public const string     TXT_END_PROTO_ENUM_FILE = "모든 타입 테이블을 proto file로 정의했습니다.";
        public const string     TXT_END_ALL_JOB = "모든 작업을 마쳤습니다.";
        public const string     FMT_NO_SETTING_FILE = "파일 경로 에러 : {0}";
        public const string     TXT_DO_SETTING = "경로 설정을 먼저 해주세요.";
        public const string     TXT_AUTO_SETTING = "자동 경로 설정 중입니다.";
        public const string     FMT_FAIL_FILE_TYPE = "파일 [{0}]이 형식에 문제가 있습니다.";
        public const string     FMT_END_LOCALIZATION_SINGLE = "{0}완료";
        public const string     FMT_ZONE_SEPERATE = "{0}_{1}";


        public const string     DATAFILETYPENAME_CONSTDATA = "ConstData";
        public const string     DATAFILETYPENAME_LOCALIZATION = "LocalizationData";

        // 파일 경로들 상대 경로로 고정

        // input files
        public const string PATH_EXCEL_DATA = @"\\ExcelData\\";
        public const string PATH_EXCEL_ENUM_DATA = @"\\ExcelData\\EnumType\\";
        public const string PATH_EXCEL_GROUP_DATA = @"\\ExcelData\\GroupData\\";
        public const string PATH_EXCEL_LOCAL_DATA = @"\\LocalizationData\\";
        public const string PATH_EXCEL_SYS_LOCAL_DATA = @"\\LocalizationData\\SystemData\\";
        public const string PATH_EXCEL_CONST_DATA = @"\\ConstData\\";
        public const string PATH_EXCEL_PROTOCOL_DATA = @"\\ProtocolData\\";

        // output files
        //public const string PATH_CLIENT_DATA = @"\\..\\ProjectS\\Assets\\_DownloadableAssets\\DataEnc\\";
        //public const string PATH_CLIENT_GROUP_DATA = @"\\..\\ProjectS\\Assets\\_DownloadableAssets\\DataEnc\\GroupData\\";
        //public const string PATH_CLIENT_LOCAL_DATA = @"\\..\\ProjectS\\Assets\\_DownloadableAssets\\Localization\\";
        //public const string PATH_CLIENT_SYSTEM_LOCAL_DATA = @"\\..\\ProjectS\\Assets\\Resources\\System_Localization\\";
        //public const string PATH_CLIENT_CS_FILE = @"\\..\\ProjectS\\Assets\\Scripts\\GameDataStructs\\AutoGenerated\\";
        //public const string PATH_CLIENT_PROTOCOL_CS_FILE = @"\\..\\ProjectS\\Assets\\Scripts\\Managers\\Manager_Network\\AutoGenerated\\";

        public const string PATH_CLIENT_ROOT = @"\..\";
        public const string PATH_CLIENT_DATA = PATH_CLIENT_ROOT + @"Content\GameContents\Data\";
        public const string PATH_CLIENT_GROUP_DATA = PATH_CLIENT_ROOT + @"GroupData\\";
        public const string PATH_CLIENT_LOCALIZATION = PATH_CLIENT_ROOT + @"Content\GameContents\Localization\";
        public const string PATH_CLIENT_SYSTEM_LOCAL_DATA = PATH_CLIENT_ROOT + @"System_Localization\\";
        public const string PATH_CLIENT_CS_FILE = PATH_CLIENT_ROOT + @"CSharpUnity\\";
        public const string PATH_CLIENT_PROTOCOL_CS_FILE = PATH_CLIENT_ROOT + @"CSharpUnity\\Protocol\\";

        public const string PATH_CLIENT_CPP_CLASS_ROOT = PATH_CLIENT_ROOT + @"Source\DataLoadLib\DataFile\";
        public const string PATH_CLIENT_CPP_DATASTRUCTURE_FILE = PATH_CLIENT_CPP_CLASS_ROOT + @"DataStructure\\";
        public static Encoding CLIENT_TEXT_CPP_ENCODING = Encoding.Unicode;


        public const string PATH_SERVER_DATA = @"\\Server\\Data\\";
        public const string PATH_SERVER_LOG = @"\\Log\\";
        public const string PATH_SERVER_SHARED_DATA = @"\\Server\\SharedStructure\\";
        public const string PATH_SERVER_PROTOCOL_DATA = @"\\Server\\Protocol\\";
        public const string PATH_SERVER_PROTOCOL_DESC_DATA = @"\\Server\\Protocol\\";
        public const string PATH_SERVER_CONST_DATA = @"\\Server\\ConstData\\";
        public const string PATH_SERVER_ADMIN_PROTOCOL_DATA = @"\\Server\\AdminServer\\";

        public static string serverName = "dev";

        /// <summary>
        /// {0} : Root(parent, current)
        /// {1} : Target
        /// </summary>
        //public const string     FMT_FOLDER = "{0}\\{1}";

        //public const string     FMT_BASIC_PATH_ASSET = "{0}\\Otome\\Assets\\";
        //public const string     FMT_BASIC_PATH_CLIENT_DATA = "{0}\\Otome\\Assets\\Resources\\Data\\AB_GameData";
        //public const string     FMT_BASIC_PATH_CLIENT_CODE = "{0}\\Otome\\Assets\\Scripts\\AutoGenerated\\GameDataStructs";

        //public const string     FMT_BASIC_PATH_EXCEL_DATA = "{0}\\ExcelData";
        //public const string     FMT_BASIC_PATH_EXCEL_ENUM = "{0}\\ExcelData\\EnumType";
        //public const string     FMT_BASIC_PATH_PROTO_ENUM = "{0}\\ProtoData";
        //public const string     FMT_BASIC_PATH_SERVER_DATA = "{0}\\ServerData";
    }
}
